# Multi-stage build
FROM node:20-alpine AS builder

WORKDIR /app
COPY ./package*.json ./
RUN npm install --production
COPY . .
RUN npm run build

# Finálny obraz
FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app/dist ./dist
RUN npm install -g serve

# Spustenie statického servera
CMD ["serve", "-s", "dist", "-l", "5173"]