services:
  backend:
    build: ./backend
    container_name: harvest-backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: harvest
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    user: '${UID}:${GID}'

  frontend:
    build: ./frontend
    container_name: harvest-frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  db:
    image: mysql:8.0
    container_name: harvest-db
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: harvest
    ports:
      - '3306:3306'
