services:
  backend:
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
    user: '${UID}:${GID}'
    volumes:
      - ./backend:/var/www/html

  frontend:
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend:/app
    command: npm run dev
