services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/var/www/html
    ports:
      - '8000:8000'
    environment:
      APP_ENV: development
      APP_DEBUG: true

  frontend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: development

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
