events {}

http {
    server {
        listen 80;

        # Presmeruj API požiadavky na Laravel
        location /api/ {
            proxy_pass http://harvest-backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Frontend (vývojový server alebo build)
        location / {
            proxy_pass http://harvest-frontend:5173/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
