FROM php:8.2-fpm-alpine as base

RUN apk add --no-cache \
    libpng-dev \
    libxml2-dev \
    oniguruma-dev \
    mysql-client \
    zip \
    unzip \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Build stage (Composer, Artisan)
FROM base as builder

WORKDIR /var/www/html
COPY . .

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# RUN composer install --no-dev --optimize-autoloader --no-interaction \
RUN composer install --optimize-autoloader --no-interaction \
&& php artisan config:cache \
    && php artisan route:cache \
    && php artisan view:cache

# Final runtime stage
FROM base

WORKDIR /var/www/html
COPY --from=builder /var/www/html /var/www/html

RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

EXPOSE 9000
CMD ["php-fpm"]
