events {}

http {
    include mime.types;
    default_type application/octet-stream;

    types {
        text/html html htm shtml;
        text/css css;
        text/javascript js;
        application/javascript mjs;
        application/json json;
        image/svg+xml svg;
        image/png png;
        image/jpeg jpeg jpg;
        font/woff2 woff2;
    }

    server {
        listen 80;

        # Statické súbory z frontend build
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html; # Pre SPA
        }


        # Backend API
        location /api/ {
            fastcgi_pass backend:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Redirect /api to /api/ to avoid 301
        location = /api {
            rewrite ^ /api/ permanent;
        }

        # Kompresia
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    }
}