events{}
http {
  include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    tcp_nopush    on; # Enable TCP nopush for better throughput
    tcp_nodelay   on; # Reduce latency for small packets

    # Optimize gzip for performance
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6; # Balanced compression level (1-9, 6 is a good default)
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml+rss text/javascript;
    
    server {
        listen 80;
        server_name 147.242.153.77; # fake IP address
        root /usr/share/nginx/html;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        index index.html index.htm index.php;
        charset utf-8;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api {
            alias /var/www/html/public;
            try_files $uri $uri/ @laravelapi;
            location ~ \.php$ {
                include fastcgi_params;
                fastcgi_pass backend:9000;
                fastcgi_param SCRIPT_FILENAME $request_filename;
            }
        }
    
    location @laravelapi {
        rewrite /api/(.*)?$ /api/index.php?$is_args$args last;
    }
    location = /favicon.ico { 
        access_log off;
        log_not_found off; 
    }
    location = /robots.txt  { 
        access_log off;
         log_not_found off; 
    }
    error_page 404 /index.php;
    location ~ /\.(?!well-known).* {
        deny all;
    }
    }
}